### ISSUE TITLE
Issues trying to recreate 

### ISSUE THREAD

**Issue by Chinothebuilder** [hyonbokan/lithology-identification-fl#1]
I am really happy to come accross your work here. But I am having issues recreating your work
Here is my code
https://github.com/Chinothebuilder/fl_xgb_flwr/blob/main/zkTrial.ipynb
I will appreciate so much if you have any solution to this issue. thank you

I get this error

WARNING :   DEPRECATED FEATURE: `FedXgbNnAvg` strategy

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
```
WARNING :   Both server and strategy were provided, ignoring strategy
INFO :      Starting Flower simulation, config: num_rounds=10, no round_timeout
Trainloaders data shape: torch.Size([23731, 17]), Label shape: torch.Size([23731])
Testloaders data shape: torch.Size([13960, 17]), Label shape: torch.Size([13960])
Data partitioned across 3 clients and 0.1 of local dataset reserved for validation.
FL experiment configured for 10 rounds with 3 client in the pool.
FL round will proceed with 100.0% of clients sampled, at least 1.
2024-06-23 19:14:16,359	INFO worker.py:1752 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'memory': 33953879655.0, 'CPU': 12.0, 'accelerator_type:L4': 1.0, 'node:__internal_head__': 1.0, 'node:172.28.0.12': 1.0, 'GPU': 1.0, 'object_store_memory': 16976939827.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 1 actors
INFO :      Initializing global parameters
INFO :      Requesting initial parameters from one random client
ERROR :     RayActorClientProxy.get_parameters() missing 1 required positional argument: 'group_id'
ERROR :     Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flwr/simulation/app.py", line 323, in start_simulation
    hist = run_fl(
  File "/usr/local/lib/python3.10/dist-packages/flwr/server/server.py", line 490, in run_fl
    hist, elapsed_time = server.fit(
  File "<ipython-input-134-f477193a3703>", line 20, in fit
    self.parameters = self._get_initial_parameters(timeout=timeout)
```

Please how can I resolve this. I am running on google colab. If you want to get more info,

**Comment by hyonbokan** [comment]
Hello.
It seems that you modified the client side of the code and the issue rises there, as error states: "missing 1 required positional argument: 'group_id'". 

Kindly check get_parameters in FL_Client class.
Hopefully it helps.

**Comment by Chinothebuilder** [comment]
Helllo, thank you so much for your reply. I could have sent this earlier but I was travelling. 
This issue happened even before I modified the get_parameter() function. I still tried to debugg by making some adjustment on the code and the error persisted. 

I just ran it again, got the same error. 
https://github.com/Chinothebuilder/Flwr_Federated_Learning/blob/main/zkTrial_(1).ipynb
I do appreciate your help so far, I just hope you can help figure out what could be wrong

**Comment by Chinothebuilder** [comment]
I can send the dataset if you would want to have a look. Thank you so much

**Comment by hyonbokan** [comment]
Hi!
It seems that Flower framework completely reworked their XGBoost FL code base. I highly recommend to view their documentation and follow their tutorial at https://flower.ai/docs/framework/tutorial-quickstart-xgboost.html.

Regarding the code you have shared, I see that it is binary classification (HeartDisease), so there could be conflict in the shape of the data matrix sent by the client and what the model expects to receive. But first review the tutorial page, I shared with you. If you still want to use my code then it requires few modifications.

**Comment by Chinothebuilder** [comment]
Thank you so much, I was able to resolve it using the newly reworked XGBoost FL code base. I so much appreciate your help.
